# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Tick Tick Done' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Tick Tick Done

	pod 'FirebaseAuth'
	pod 'FirebaseFirestore'


end
